name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "This is a variable"
    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"

      - name: Show the variable
        run: echo 'La variable est ${{ env.MY_VARIABLE }}'

      - name: Afficher le secret (ne sera pas visible)
        run: echo "Secret reçu >> ${{ secrets.MY_SECRET }}"

      - name: Créer le fichier hello.txt
        run: echo "Hello world" > hello.txt

      - name: Lire le contenu de hello.txt
        run: cat hello.txt
