name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: "This is a variable"

    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"

      - name: Show the variable
        run: echo "La variable est : ${{ env.MY_VARIABLE }}"

